// vue-app/src/components/Board.vue
<template>
<div>
  <div class="board-row" v-for="r in 3" :key="r">
        <Square
          v-for="c in 3"
          :key="(r-1)*3 + (c-1)"
          :index="(r-1)*3 + (c-1)"
          :value="squares[(r-1)*3 + (c-1)]"
          :click="click"
        />
  </div>
</div>
</template>

<script>
import Square from './Square.vue'

export default {
  name: 'Board',
  props: {
    squares: Array,
    click: Function,
  },
  components: {
    Square
  },
}
</script>

<style scoped>
.board-row:after {
  clear: both;
  content: "";
  display: table;
}
</style>

// react-app/src/Board.js
import React from 'react';

var Square = (props) => (
      <button className="square" onClick={() => props.onClick()}>
        {props.value}
      </button>
);

var Board = (props) => {
    var rows = [];
    for(var r = 0; r < 3; r++) {
      var cols = [];
      for(var c = 0; c < 3; c++) {
        var i = r*3 + c;
        cols.push(<Square
          key={i}
          value={props.squares[i]}
          onClick={props.onClick.bind(this, i)}
        />);
      }
      rows.push(
        <div key={r} className="board-row">
          {cols}
        </div>
      );
    }
    return (<div>{rows}</div>);
};

export default Board;
